### ISSUE TITLE
Error with duplicate objective names

### ISSUE THREAD

**Issue by ellepin** [hrntsm/Tunny#132]
## Describe the bug

When there are multiple target values, the function of the output tab does not work if there are names of the same objective name.
The same does not work if there are two empty objective names.

## To Reproduce

1.Open sample.gh.
2. Delete and empty the names of objective "v0" and "v1".
3. Run optimization in Tunny.
4. From the output tab of Tunny, click on "Pareto solutions"
5. The process bar stops in the middle of the process and nothing happens after waiting.

When started in debug mode, "System.ArgumentException" is generated and the program is terminated. Error occurs when the "objectives" variable in dictionary format tries to have the same key.

## Environment

- OS: Windows10
- Rhino: 7.24.22308.15001
- Tunny: v0.5.0

**Comment by hrntsm** [comment]
@ellepin 
Thanks for the report. I have checked about the bug and will fix it. 
If an incorrect objective nickname is entered, an error will be generated.

**Comment by hrntsm** [comment]
The Tunny window is not shown by outputting an error when there is a problem as follows.

![video](https://user-images.githubusercontent.com/23289252/208237208-29e3b4f3-1070-4358-b6c7-addf7f4fb425.gif)

**Comment by hrntsm** [comment]
@ellepin 
If you would like to review the fixed version, please download it from Artifacts at the bottom of the following page.
https://github.com/hrntsm/Tunny/actions/runs/3719626356

**Comment by ellepin** [comment]
@hrntsm 
Thanks for fixing the bug. The fixed version worked.
Thank you again for developing this wonderful component.
