### ISSUE TITLE
Storage file path should be surrounded by quotation marks

### ISSUE THREAD

**Issue by Knuttatutta** [hrntsm/Tunny#142]
I've placed my Tunny plugin in a folder where one of the parent folders has a space, so in the following line: `dashboard.StartInfo.Arguments = @"sqlite:///" + _settings.StoragePath;` 
in the `VisualizeTab`, the path has a space, which gives an error when attempting to run the command in the terminal

![image](https://user-images.githubusercontent.com/48133001/213711242-1b687d88-78d5-4fff-8dae-8e2f4a1f2825.png)

**Comment by hrntsm** [comment]
Hi @Knuttatutta,
Thank you for your report.
I will correct the relevant part of the report.

**Comment by hrntsm** [comment]
@Knuttatutta 
Merged PR. So I will close this issue.
Thank you once again.
