### ISSUE TITLE
Error: Cannot commit optuna session

### ISSUE THREAD

**Issue by Knuttatutta** [hrntsm/Tunny#145]
## Describe the bug

Ran into the error in screenshot below. 

![image](https://user-images.githubusercontent.com/48133001/216594735-2c46ff50-5e5f-477b-bc08-9a89fcccb80e.png)

Seems like a strange error to run into.. I'm running an optimisation with the sliders below as input, and with 6 objectives. After roughly 460 trials I ran into this error. I restarted Rhino and ran it again and the error occurred again after a few trials.
![image](https://user-images.githubusercontent.com/48133001/216596349-58ecf261-d42e-4c99-b374-7eafe57ad832.png)

## To Reproduce

Unfortunately I can't share the model for testing... But maybe you can help me debug it? How can I see the session details that it's trying to commit? Is it even possible since it's occurring in `optuna`? 

## Environment

- OS: Windows
- Rhino Version: 7
- Tunny Version: 0.6.0

**Comment by hrntsm** [comment]
Thanks @Knuttatutta.

This problem occurs when saving Optuna optimization results to RDB.
I am aware of the occurrence of this error as I am experiencing the same error with my own optimization.

Currently Tunny is using Optuna's feature to save in sqlite format and this seems to be the cause. However, I am not sure yet. Optuna supports saving in file formats other than sqlite, so I am considering including the use of that as well.

Could you please answer the following questions to confirm the error?
- Are you including geometry in the optimization Attribute?
- What is the size of the optimization result file (fish.db by default)?

**Comment by Knuttatutta** [comment]
Okay great that you are aware already of this. And sorry for duplicating the issue, didn't notice the other one!

So when I ran into this error there are no attributes at all given, so no geometries. And the size of the `Fish.db` file was around 19 MB at the time it happened I think. Later I have ran other studies, so it's currently 25 MB.

I do see that optuna has released version 3.1.0 that includes updates to the storage backend, so could be worth taking a look into that maybe?

**Comment by hrntsm** [comment]
Thank you for the answers to my questions.
I thought the error was caused by the large amount of attribute information, but it seems not.

In optuna 3.1 a new storage format, JournalStorage, has been implemented and after trying it out I do not expect this problem to occur because unlike sqlite it is simply ASCII JSON.
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.JournalStorage.html#optuna.storages.JournalStorage

So I think switching to it is a good solution to this problem. However, there are many parts of Tunny's UI that are written assuming the use of sqlite, so I have not been able to work on them.

**Comment by hrntsm** [comment]
hi @Knuttatutta ,

This is a workaround for this problem, but I have implemented an in-memory mode of optimization in conjunction with previous requests for higher speed.
In-memory mode, as the name implies, does not save the optimization files during optimization, so the problem that is the subject of this issue should not occur.
In this mode, the results are saved only once, when the optimization is finished.
If you want to try it, use the following build with CI as it is a development release.

https://github.com/hrntsm/Tunny/actions/runs/4144729424

Of course, I will continue to work toward a substantive solution to the problem.

**Comment by Knuttatutta** [comment]
Hi @hrntsm ,
I was trying out the in memory mode, and it does make the optimisation go faster, and I indeed don't run into the error while optimising, but unfortunately I did run into the error at the end when it does save all the data to the database file, as you can see in the picture below. This happened when I manually stopped the optimisation instead of waiting it to finish the trials, but I don't expect that to make a difference since in the end I expect it to attempt to save the data in the same way.

![image](https://user-images.githubusercontent.com/48133001/222152308-69dfe0d3-1e21-4c05-99f7-50601d1d7306.png)

**Comment by hrntsm** [comment]
Hi @Knuttatutta,

In addition to the existing sqlite-based storage, journal storage, a new format in Optuna v3.1, is now supported.
JournalStorage by setting the save format to .log as follows.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/23289252/222736859-ef9f0de8-c92a-4881-a44b-03f6168c972a.png">

I tried with the gh file which had an error after about 500 trials with the previous sqlite storage, but by using JournalStorage, I confirmed that there was no problem until 3000 trials. Maybe the optimization will continue to progress without problems after this.

You can try the CI build below. Could you check to see if JournalStorage solves this problem in your environment as well?
https://github.com/hrntsm/Tunny/actions/runs/4324035857

**Comment by Knuttatutta** [comment]
Hi @hrntsm ,

Great, I'll try it out right away! 
Is JournalStorage also supported by the dashboard? So can I run the optimisation not in memory and use the dashboard while it's running?

**Comment by hrntsm** [comment]
Hi @Knuttatutta, Thanks for checking it out right away.

> Is JournalStorage also supported by the dashboard? So can I run the optimisation not in memory and use the dashboard while it's running?

Yes, Dashboard is supported even when using JournalStorage; once you press the "Open Optuna-Dashboard" button, it will work regardless of storage.

> So I'm getting the following error when stopping the optimisation manually.

Thanks for sending me the error screen! I was able to pinpoint the cause right away.
It was caused by Tunny's UI accessing the log file before Optuna's optimization and saving process to the log file was completely finished.
I fixed it so that even when other processes are accessing the log file, the UI accessing the log file does not cause an error.

How would this version work?
https://github.com/hrntsm/Tunny/actions/runs/4328908737

**Comment by Knuttatutta** [comment]
Hi, @hrntsm 

So I can confirm that with the JournalStorage I don't run into any issues with storing the data, and the dashboard also works fine!

**Comment by hrntsm** [comment]
Thanks @Knuttatutta  for checking!
Thanks to your help I have been able to solve this issue, which has been a problem for a long time.

Please let me know if there is anything else I can do to improve it.

**Comment by Knuttatutta** [comment]
@hrntsm thank you for fixing it!
Happy to help, especially since Tunny appears to be the tool we want to use in some of our design exploration/optimisation workflows
