### ISSUE TITLE
Enable study.best_trials and Compute2dHypervolumeRatio to be toggled enabled or disabled

### ISSUE THREAD

**Issue by hrntsm** [hrntsm/Tunny#152]
### Discussed in https://github.com/hrntsm/Tunny/discussions/151

<div type='discussions-op-text'>

<sup>Originally posted by **Knuttatutta** March  7, 2023</sup>
Hi @hrntsm ,

Do you also have issues with the optimisation slowing down quite quickly until it becomes extremely and prohibitively slow? In the beginning a trial can take 0.05 seconds, and at 500 trials it can take 0.5 second..

This happens with all types of storage method (.db, .log, and in memory). In memory is of course faster at first, but it also really slows down.

I haven't looked into yet what might be causing it, but I was wondering if you were maybe aware of it and the cause?

Edit:
I'm not 100% sure, but with or without geometry attributes doesn't seem to affect the slowing down behaviour. I do think it's maybe a tiny bit slower in general with geometry, but I don't think it affects how it's slowing down. But again, not completely sure</div>

**Comment by Knuttatutta** [comment]
@hrntsm indeed when I disable those two operations, it goes a lot faster and I don't think there's any notable slowdown

**Comment by hrntsm** [comment]
Hi @Knuttatutta 

I added a Checkbox to the UI to see if it should be used or not. 
If not checked, best_trials, etc. will not be computed as shown in the code below, which solves this issue.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/23289252/224477714-15156d8b-e8e3-48e0-8100-5f542305c2ec.png">

https://github.com/hrntsm/Tunny/blob/feature/toggle-realtime-opt-result-ui/Tunny/Solver/Algorithm.cs#L289
```cs
  private void ComputeBestValues(dynamic study, int trialNum, out double[][] bestValues, out double hypervolumeRatio)
  {
      if (Settings.Optimize.ShowRealtimeResult)
      {
          dynamic[] bestTrials = study.best_trials;
          bestValues = bestTrials.Select(t => (double[])t.values).ToArray();
          hypervolumeRatio = trialNum == 0 ? 0 : trialNum == 1 || ObjNickName.Length == 1 ? 1 : Hypervolume.Compute2dHypervolumeRatio(study);
      }
      else
      {
          bestValues = null;
          hypervolumeRatio = 0;
      }
  }
```

The build with CI is as follows
https://github.com/hrntsm/Tunny/actions/runs/4391716591

**Comment by hrntsm** [comment]
The issue is closed as it appears to be working.
