### ISSUE TITLE
Fresh Install - Missing Module Optuna

### ISSUE THREAD

**Issue by tmwarchitecture** [hrntsm/Tunny#163]
Just downloaded from github, downloaded packages the first time after I double clicked the component, seemed fine. When I pressed "RunOptimize" it told me "missing module optuna". The component does nothing after that.

Thanks
Tim

**Comment by hrntsm** [comment]
Hi @tmwarchitecture 

Thanks for the download.
Could you please check [this discussion](https://github.com/hrntsm/Tunny/discussions/154) first?

**Comment by tmwarchitecture** [comment]
Yes, thats exactly my issue, thanks.
