### ISSUE TITLE
Tunny_v072_include_python still require "Installing Python package depending on Tunny"

### ISSUE THREAD

**Issue by netsonicyxf** [hrntsm/Tunny#177]
## Describe the bug

After installing Tunny using "Tunny_v072_include_python.zip", then run Tunny, iy shows
![image](https://github.com/hrntsm/Tunny/assets/43513391/2570ed80-1735-42e5-b1a3-0ef328c365e6)

## Environment

- OS: Win 10 x64
- Rhino Version 7.27
- Tunny Version: 0.72 with python

**Comment by hrntsm** [comment]
Hi @netsonicyxf ,

To help us identify the problem, please tell me the following

1. Do you mean Tunny does not work?
2. Does this mean that Tunny is working fine even if this window appears every time?
3. Have you tried a version that does not "include_python"?

**Comment by netsonicyxf** [comment]
1. Yes, when running Tunny, it shows
`Tunny runtime error:
Please send below message (& gh file if possible) to Tunny support.
If this error occurs, the Tunny solver will not work after this unless
Rhino is restarted.
""Delegates" Type initializer raises an exception`
2.  Tunny doesn't work  at all
3. I tried 0.72 w/o python, it stuck at "Installing Python package depending on Tunny" as shown in the 1st post.
4. Yes, I think follow the instructions.

**Comment by hrntsm** [comment]
w/o Python Tunny not working, have you tried the following Discussion?
https://github.com/hrntsm/Tunny/discussions/154

**Comment by hrntsm** [comment]
I'm closing because I haven't heard back from you in a long time.
