### ISSUE TITLE
Can't run Tunny optimisation

### ISSUE THREAD

**Issue by karimosling** [hrntsm/Tunny#236]
![image](https://github.com/hrntsm/Tunny/assets/31615908/c37131e5-3d95-4525-ac4c-4bf06a0bcf3a)

I have had issues with running tunny in a large code. Created a very simple Grashopper-script to try. The image shows the error message.

**Comment by hrntsm** [comment]
Hi @karimosling 

Can you please run the following version with the logging level set to verbose so I can confirm what is happening in your environment?

https://drive.google.com/file/d/18cdQpZjaYaLHZY9hEDtK4onphDmUtpm4/view?usp=sharing

![log](https://github.com/hrntsm/Tunny/assets/23289252/c8246576-b3d7-4b8d-9f60-426362d8732e)

The log file will be output to the following path, so please send that as well.
`C:\Users\[USER NAME]\.tunny_env\logs`

**Comment by karimosling** [comment]
Hi @hrntsm,

I have now tried to run Tunny again, the same error occurs, the log tile is attached:

[log_20240207.txt](https://github.com/hrntsm/Tunny/files/14194631/log_20240207.txt)

**Comment by hrntsm** [comment]
Hi @karimosling 

It seems that you have set the file where the optimization results are saved to the folder that is linked to onedrive, but that can cause errors, so could you please try the normal folder?

**Comment by hrntsm** [comment]
@karimosling 
Thanks for the confirmation.
I will look into it as I can't immediately think of the cause.

**Comment by hrntsm** [comment]
I checked and it looks like maybe Tunny is failing to start the Python it is using.
I'll see what I can do.

**Comment by hrntsm** [comment]
Fix this problem to change python initialize method.
This change include v1.0.
