### ISSUE TITLE
Launching Optuna Dashboard from Tunny

### ISSUE THREAD

**Issue by reinhardt5160** [hrntsm/Tunny#293]
### Expected behavior

I assume I'd see the dashboard open as it did with previous versions on Tunny. This is the error I get: 
![Screenshot 2024-05-13 140334](https://github.com/hrntsm/Tunny/assets/155990090/a28ed6c7-18d6-47d5-9612-39f15605d962)

### Environment

- OS: Windows 11
- Rhino version: 7
- Tunny version: 0.11.1

### Steps to reproduce

I am running a daylighting simulation and using Tunny to iterate through a multi-objective problem. This process worked and allows for a dashboard launch with earlier versions of Tunny (I believe 8.2). I can still export the models and deconstruct but cannot access the dashboard.
![Screenshot 2024-05-13 140629](https://github.com/hrntsm/Tunny/assets/155990090/9e231a64-ba50-4022-9640-6d70d87151fa)

### Additional context (optional)

Perhaps this is an IT issue blocking the dashboard from loading

**Comment by hrntsm** [comment]
Hi @reinhardt5160 

It seems that an error is occurring because the folder name contains a space, like "xxx inc". It used to be supported, but it appears that the support was dropped somewhere along the way.
I'll check it

**Comment by hrntsm** [comment]
@reinhardt5160 

I fixed containing space issue. Could you try below version?
https://github.com/hrntsm/Tunny/actions/runs/9072508767
<img width="1173" alt="Screenshot 2024-05-14 at 11 00 41" src="https://github.com/hrntsm/Tunny/assets/23289252/db098bd8-8689-41ad-890b-6570efd7b639">

**Comment by hrntsm** [comment]
There is no response, so I will close it.
Please reopen if progress is made.

This fix has been included in v0.12.0.
