### ISSUE TITLE
Tunny V0.11.1 Python Installer pop up is not running

### ISSUE THREAD

**Issue by beatlesthan** [hrntsm/Tunny#295]
### Expected behavior

Python Installer pop-up is not happening and then hit run optimize shows "No module named Optuna". Moreover, I see this forum "Automatic python library download using pip does not work #154" but can not fix it

### Environment

- Windows:
- Rhino version: 7
- Tunny version: Tunny v0.11.1

### Error messages, stack traces, or logs

![image](https://github.com/hrntsm/Tunny/assets/111628529/0f289a68-f376-4085-bff7-23a44a3a9d05)

### Additional context (optional)

"Automatic python library download using pip does not work #154"
Merge pull request #162 from hrntsm/fix/storage-handling #199

**Comment by hrntsm** [comment]
Hi @beatlesthan 

Could you please try out Tunny from the Artifact in the link below?
https://github.com/hrntsm/Tunny/actions/runs/9105819195/artifacts/1507733151

This version has a Python installation button. Could you please test if it can be properly installed from this button?

![image](https://github.com/hrntsm/Tunny/assets/23289252/f0068078-9ea2-4248-985f-932925e865dc)

**Comment by beatlesthan** [comment]
I'm not sure what mistake something and also show "No module name Optuna "

![image](https://github.com/hrntsm/Tunny/assets/111628529/ddaaf5f7-0308-4d09-95d5-31c488d6d777)

**Comment by hrntsm** [comment]
@beatlesthan 
Do you mean that the installation option is not displayed even when using the version mentioned above?

**Comment by beatlesthan** [comment]
Yes,Pls

**Comment by hrntsm** [comment]
Could you please uninstall all existing Tunny instances, delete the .tunny_env folder in your UserProfile, and then reinstall it?
In my environment, there is an installation button, so I can't tell the difference.
After reinstalling, please also send a log file with the verbosity set to verbose mode.
https://graceful-stag-dae.notion.site/Tunny-Release-Note-v0-11-125bbf8f18e04588a4700d0d1f199fd4#b274dba036514836a7eef7467c2bf3ca

**Comment by hrntsm** [comment]
There is no response, so I will close it.
Please reopen if progress is made.
